### ISSUE TITLE
Missing index-attribute in disclaimer and general_information

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb#1387]
The tables `disclaimer` (Class `Disclaimer` respectively) and `general_information` (Class `GeneralInformation` respectively) don't have an index-attribute whereas in the correspoding data model (http://models.geo.admin.ch/V_D/OeREB/OeREBKRMkvs_V2_0.ili) those classes do have such an attribute (called `AuszugIndex`). Have these attributes been omitted intentionally or is this a bug?

**Comment by vvmruder** [comment]
Hi @peterschaer We skipped this because the federal data does not deliver it http://models.geo.admin.ch/V_D/OeREB/OeREBKRM_V2_0_Texte_20211021.xml
In addition http://models.geo.admin.ch/V_D/OeREB/OeREBKRMkvs_V2_0.ili is a fed suggestion which we customized to our needs. We can think about introducing the index on the elements in question.

As addition on that: In the moment this means pyramid_oereb must sort on theses index values on the server side because the DataExtract does not know about the index. And this means the clients (dynamic/PDF) need to respect server sided sorting.

Are you ok with that?

**Comment by peterschaer** [comment]
That's ok for me. Thanks.

**Comment by vvmruder** [comment]
@peterschaer Maybe I described it not correctly. In the moment pyramid_oereb does not support sorting via index on the elements in question. Should we put it in the pipe to implement this?

**Comment by peterschaer** [comment]
Sorry for the misunderstanding. I should not have closed the issue.

As the federation does provide this information in http://models.geo.admin.ch/V_D/OeREB/OeREBKRM_V2_0_Texte_20211021.xml (the attributes AuszugIndex are mandatory in https://models.geo.admin.ch/V_D/OeREB/OeREBKRMkvs_V2_0.ili) pyramid_oereb should make use of it and therefore implement the sorting.

**Comment by vvmruder** [comment]
Update to clarify and spec the problem:

- [ ] compare current version of federal defined [organization schema model](http://models.geo.admin.ch/V_D/OeREB/OeREBKRMkvs_V2_0.ili) and the pyramid_oereb [main schema](https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/contrib/data_sources/standard/models/main.py) regarding the attribute `AuszugIndex` and top up application schema where necessary with attribute `extract_index`
- [ ] Update the records with the new attribute `extract_index`
- [ ] Make sure all sources and readers handle it correctly (keep in mind core sources/readers and all the contrib ones)
- [ ] make sure to update import scripts where necessary (especially take care of correct handling of [federal data](http://models.geo.admin.ch/V_D/OeREB/OeREBKRM_V2_0_Texte.xml)-it does not contain the index for some reason in the entities in question)
- [ ] For rendering (JSON,XML,PDF) this attribute wont be exposed since the extract index is not available in the extract model. We need to handle it as a soft sort index. The elements are sorted after it by the server but are not exposed to any clients. The clients need to respect and NOT CHANGE the sort delivered by server. => This is not the best solution but will work until the extract model is improved by the fed

**Comment by voisardf** [comment]
@mki-c2c @michmuel  first one having time to finish it :)

**Comment by svamaa** [comment]
https://github.com/openoereb/pyramid_oereb/pull/1753
