### ISSUE TITLE
possibly need to fix legend entry collection in print proxy

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#1477]
possibly need to fix legend entry collection in print proxy. Legend entries might have the same type code but a different ID. So selection by type code is not enough any more.

_Originally posted by @vvmruder in https://github.com/openoereb/pyramid_oereb/issues/1463#issuecomment-1018354643_

**Comment by jwkaltz** [comment]
@vvmruder I think this is the issue you mentioned yesterday, is that right? Do we have an example for that? Maybe from @voisardf or @kdeininger ?

**Comment by vvmruder** [comment]
Yes. It is. Example can be found here: https://github.com/openoereb/pyramid_oereb/pull/1505#issuecomment-1041490213

**Comment by jwkaltz** [comment]
Thanks, we will have a look at it.

**Comment by marionb** [comment]
@voisardf or at @vvmruder what is the the expected behavior? Is it that there are two legend entries in this case?

Currently what I see in the code and in the extract example from @voisardf is: if the TypeCode of two entries are the same they get "added up". Meaning the information about the Point and the Area is contained in the same entry:

```
Legend:
	AreaShare		"700 m²"
	Geom_Type		"NrOfPoints"
	LegendText		"Pollué, pas d'atteinte nuisible ou incommodante à attendre"
	NrOfPoints		"1"
	PartInPercent	        "28.2%"
	TypeCode		"StatusAltlV1"
```
In the templates this is not so well reflected because the space used to print `NrOfPoints` is the same as for `AreaShare` and `LenghtShared`. What is printed depends on the `Geom_Type`.
https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print/mapfish_print.py#L481-L489

I am not quite sure why this is done this way. Was there ever a spec for this?

**Comment by voisardf** [comment]
@marionb : Sorry, I was about to prepare the getspec json of this extract for you, if that is helpful?
Yes, the problem here is that two two restrictions with the same TypeCode but different geometries are added up and only one of the two types appears.
We should have seperate entries in function of the geometry type:
- in this case we should have a point and an area legend entry though it's the same type of pollution
- in cases where you have the same TypeCode and the same geometry the elements should be summed up. (real estate 3380 of Colombier NE (Milvignes) - CH741299773294 (multiple points); real estate 1474 of Bôle (Milvignes) - CH107712889935 (multiple areas)

**Comment by voisardf** [comment]
Already in the old version this difference should have been made, but I'm not sure if we implemented it correctly. That should be visible in cantons that use pyramid_oereb 1.8.1 and higher I guess

**Comment by marionb** [comment]
@voisardf Thanks the explanation helps to continue. I think it might be wrong then as it is.I don't need the getspecs I already have some from her: 
But it is hard to reconstruc something in our DB. Perhaps I'll just add test ;-)
