### ISSUE TITLE
The response from the GetVersions function is incorrect

### ISSUE THREAD

**Issue by sitj-marc** [openoereb/pyramid_oereb#1695]
Hello,
I've updated pyramid_oereb to the latest version 2.4.1 and while testing, I found that the response from the GetVersions function is incorrect, the response is "extract-2.0" when the response should be "2.0

![image](https://user-images.githubusercontent.com/3088758/216012405-220a3d04-2bea-4a97-bd90-44fe8c17a243.png)

I remember that we had this issue before in one of the oldest versions.

Thank you and good day

Cheers

**Comment by michmuel** [comment]
The version string was changed because the docs (https://www.cadastre.ch/content/cadastre-internet/de/manual-oereb/service/webservice/_jcr_content/contentPar/tabs_copy_copy_copy_/items/dokumente/tabPar/downloadlist/downloadItems/436_1475415873601.download/Weisung-OEREB-XML-Aufruf-de.pdf) specify in chapter 3.4 the version to be "extract-2.0".

**Comment by sitj-marc** [comment]
That's great, thank you very much for your feedback and clarifications and have a nice day.

Cheers
