### ISSUE TITLE
Provide new index attributes

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#1706]
Regarding to #1387 (please read also there for more context) we want to implement the attributes in question with the following spec:

- [ ] compare current version of federal defined [organization schema model](http://models.geo.admin.ch/V_D/OeREB/OeREBKRMkvs_V2_0.ili) and the pyramid_oereb [main schema](https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/contrib/data_sources/standard/models/main.py) regarding the attribute `AuszugIndex` and top up application schema where necessary with attribute `extract_index` `NOT NULL`
- [ ] Update the records with the new attribute `extract_index`
- [ ] Make sure all sources and readers handle it correctly (keep in mind core sources/readers and all the contrib ones)
- [ ] make sure to update import scripts where necessary (especially take care of correct handling of [federal data](http://models.geo.admin.ch/V_D/OeREB/OeREBKRM_V2_0_Texte.xml))
- [ ] For rendering (JSON,XML,PDF) this attribute wont be exposed since the extract index is not available in the extract model. We need to handle it as a soft sort index. The elements are sorted after it by the server but are not exposed to any clients. The clients need to respect and NOT CHANGE the sort delivered by server. => This is not the best solution but will work until the extract model is improved by the fed
- [ ] refactor code and tests regardingly

**Comment by vvmruder** [comment]
@jwkaltz may I ask you to provide PSC with a quote for that?

**Comment by jwkaltz** [comment]
> @jwkaltz may I ask you to provide PSC with a quote for that (the quote will be discussed at the end of march in the user group meeting)?
> 
> Let me know if you need further information.

Yes, we will have a look and notify in case of questions.

**Comment by mki-c2c** [comment]
Hello, I have gotten into preliminary analysis.
I will just share some hypotheses for further development:

- the new attributes shall be of type NOT NULL in the DB, alright. The import scripts (from FED data are very rigid, so I would rather not modify them but add a constraint on the table, that a sequence generated index is added unless the index is given in the data.
- if needed, existing databases will be updated with a simple script, instead of a powerful DB migration tool
