### ISSUE TITLE
Wrong timestamp for archived pdf

### ISSUE THREAD

**Issue by voisardf** [openoereb/pyramid_oereb#1717]
In line https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print/mapfish_print.py#L175 a time delta of +2h is added to utcnow() to define the filename for archiving PDF extract.
This composes a wrong timestamp regarding the actual creation date of a PDF (local time) that should be used and differe from the creation date in the logs too. It also uses the 12h notation and not the 24h. 

The date in the filename, the creation_date in the PDF (https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print/mapfish_print.py#L243) and the date in the log files should be identical.

**Comment by marionb** [comment]
@voisardf 
For me the time-date used in the archive name is correct (at least in the summer half Year as it is at the moment).
When studying the code I noted the following:
- What is set for the Archive in [line 175](https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print/mapfish_print.py#L175 ) the timezone UTC+2 which is correct for Switzerland in summer but not during winter (then it should be UTC+1).
- What is set in the json and is also used for the general pdf file name and footer is currently off by 2h - in my case this is wrong. Is this correct in your system?
- The setting for the 24h is correct on my side (it is using 24h notation not 12h) and I also see this in the resulting PDF  can you check if this is really still an issue for you?

I totally agree that we should use the same time-date, so that it is the same in both places. My question is which one? For me the one that is generated in the MFP proxy on line 175 is more correct than the other one that comes from the json. (From the issue I take that this is the opposite for you?)

**Comment by voisardf** [comment]
@marionb Thanks. I have to check that again on our side. I'll get back to you soon

**Comment by voisardf** [comment]
@marionb Yes, for me it's the creation_date on line 243 which should be used as in my opinion it should always be correct because it's the one generated for the json used to establish the pdf.
For my better understanding, why do you think that the one on line 175 is more appropriate?

**Comment by marionb** [comment]
@voisardf Actually I don't think it is more appropriate, on my system it is just the time that resembles what I see on my PC clock at least at the moment. 
I think it is a good idea to use the one from line 243 which comes from the json then we have more consistency. And only one place to fix if that is needed :-) 

I will take a look and propose a PR.

**Comment by voisardf** [comment]
@marionb thanks for the feedback and ok for fixing it
