### ISSUE TITLE
Refine GML objects

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#742]
Use Polygon and Line points as POSLIST instead of pos. This will reduce data a lot.

Exterior of polygons should be removed, since it is not necessary.

**Comment by kdeininger** [comment]
> Use Polygon and Line points as POSLIST instead of pos. This will reduce data a lot.

Would be a useful improvement :+1: 

> Exterior of polygons should be removed, since it is not necessary.

We cannot remove the exterior of a polygon as it is its outer boundary. The interior part has to be removed, if the polygon has no interior rings. But interior rings may occur, since there are real estate and restriction geometries containing holes.

Real estate with interior rings:
https://geoview.bl.ch/oereb/?map_x=2601433.224&map_y=1254504.407&map_zoom=6&egrid=CH150183771296

Noise sensitivity levels with interior rings:
https://geoview.bl.ch/oereb/?map_x=2635095.180&map_y=1257830.011&map_zoom=10&egrid=CH907008986193
