### ISSUE TITLE
PDF extract without PLR

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb#774]
We have cases where there is a real estate without any public law restriction. In these cases the pdf extract contains a page with an empty map and an empty table (s. p.4 in [1_DE_PYRAMID.pdf](https://github.com/openoereb/pyramid_oereb/files/2832244/1_DE_PYRAMID.pdf)). This page is confusing and should be omitted.

**Comment by svareg** [comment]
Hello, 

At BS we've just spotted the same problem.
And I just looked at OEREB-Kataster in BL, it can be reproduced here too.
Is there any simple correction or workaround ?

Thanks !

**Comment by vvmruder** [comment]
For me there are 2 possible solutions to be discussed:

1. We return a valid HTML code 404 (HTTP not Found) if there was no PLR matching.
2. We return a correctly styled empty PDF (this would need more clarification how it should look).

Solution 1 is obviously the more easy one.

Discussion opened... :+1:

**Comment by peterschaer** [comment]
I don't think Solution 1 is a good one.  I think that the user expects a PDF like this one ([CH373540414688.pdf](https://github.com/openoereb/pyramid_oereb/files/2914827/CH373540414688.pdf)) if there is no PLR on a real estate. In the TOC on page 2 the user gets all the relevant information. This is much better than a 404 code. Why should we not be able to produce a PDF in those cases?

**Comment by peterschaer** [comment]
The PDF we get from pyramid_oereb and mapfish_print is actually perfect for me except for the superfluous page 3 in the example I added at the start of this issue.

**Comment by voisardf** [comment]
Well, - normally there should be no property without restrictions I guess as there should be at least some data regarding the LandUse. Now, I see that the case can appear if not all data is already available.

Personnally I think we have the legal obligation to produce an PDF, even if there are no restrictions (available). Otherwise I'd agree that an 404 would a handy solution...

my 2 cents

**Comment by svareg** [comment]
A 404 error can be a quick temporary solution, to prevent the generation of a dirty PDF. 
But I agree with @peterschaer, I feel we should be able to generate a correct PDF file even if there isn't any concerned PLR, so that the user gets what he is waiting for : a document that indicates that there is no concerned PLR.

@voisardf : I'm not 100% sure, but I think there can be cases where there isn't any concerned PLR, even with landuse. For example is we generate a PDF for a street parcel.

**Comment by vvmruder** [comment]
Indeed. I agree on solution 2. Solution one would be a temporary fix only.

@voisardf Do you have any idea how this could be fixed?

**Comment by voisardf** [comment]
I have to admit I'm not up to date with my installation as I am lacking the checksum column db update.
But for the oereb_mfp to work,  I think that we just need to add conditional printing for the TOCPageLabel in the toc.jrxml and also for the topicpage.jrxml in the pdfextract.jrxml (Print When).

**Comment by jwkaltz** [comment]
Fixed in #846
