### ISSUE TITLE
URLs are encoded in XML-Dataextracts

### ISSUE THREAD

**Issue by pramisters** [openoereb/pyramid_oereb#820]
Contrary to the JSON dataextract (see BL) pyramid_oereb encodes the URLs in XML dataextract.
This poses a problem when using XML2PDF Service (from GIS Daten AG) as this service expects decoded URLs.
pyramid_oereb should neither encode URLs when requesting an XML extract.

**Comment by svareg** [comment]
I don't know XML2PDF, but I think we cannot have 100% not encoded urls in XML Dataextracts, because this will generate invalid XML. 

The character "&" must be encoded as &amp; for example, because it it no authorized in valid XML. And therefore XML2PDF will have to decode it anyway. Can XML2PDF do this ?

**Comment by pramisters** [comment]
You are right, "&" must be encoded in XML, but that's the only one in the context our XML-Dataextract. For all others like ":", "/", "," it's not necessary (to encode in XML) and therefore useless that pyramid_oereb encodes and XML2PDF decodes them again.

**Comment by vvmruder** [comment]
Indeed. This was the problem. I knew there was one...

How should we treat this? In the end it will be a ugly solution to only encode "&" in the URL.

What's your opinion on that @kdeininger

**Comment by kdeininger** [comment]
I think, a "custom" encoding of `&` characters only would be a dangerous solution, because other invalid characters could occur and break the XML validation.

An encoded URL ensures valid XML content and decoding should be possible with nearly every common coding language. In my opinion, decoding URLs in XML2PDF would be the best solution.

**Comment by pramisters** [comment]
It seems highly unlikely that other invalid characters occur in the XML as <, > and " are the only characters (apart from &) that have to be encoded in XML.
If this issue could be solved with a print proxy (for XML2PDF) in pyramid_oereb as  @vvmruder  suggested , that's fine for me.

**Comment by jwkaltz** [comment]
I am closing this issue: to my understanding, we can not / will not change the XML extract in this manner. Any adaptations for calling the XML2PDF service with the pyramid_oereb extract XML should be handled by the xml2pdf proxy code.
